version: '3'
services:
  pbx:
    container_name: pbx
    build:
      context: pbx/.
      dockerfile: Dockerfile
    ports:
      - 5060:5060
      - 5060:5060/udp
      - 20100-20180:20100-20180/udp
    volumes:
      - ./tmp/pbx:/var/spool/asterisk
  rtmp:
    container_name: rtmp
    build:
      context: rtmp/.
      dockerfile: Dockerfile
    ports:
      - 1935:1935
      - 8080:80
  capture:
    image: ghcr.io/pkshatechnology/orkaudio:master
    cap_add:
      - NET_RAW
      - NET_ADMIN
    network_mode: "service:pbx"
    volumes:
      - ./capture/logging.properties:/etc/orkaudio/logging.properties
      - ./capture/config.xml:/etc/orkaudio/config.xml
      - ./tmp/capture:/var/log/orkaudio
    depends_on:
      - pbx
      - rtmp
